In [1]:
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import numpy as np
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf

2022-06-04 18:11:01.359641: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [2]:
ddir = '/data/stock/'
d2012 = pd.read_csv(ddir + 'stock.KOSPI.KOSDAQ.2012.csv')
d2013 = pd.read_csv(ddir + 'stock.KOSPI.KOSDAQ.2013.csv')
d2014 = pd.read_csv(ddir + 'stock.KOSPI.KOSDAQ.2014.csv')
d2015 = pd.read_csv(ddir + 'stock.KOSPI.KOSDAQ.2015.csv')
d2016 = pd.read_csv(ddir + 'stock.KOSPI.KOSDAQ.2016.csv')
d2017 = pd.read_csv(ddir + 'stock.KOSPI.KOSDAQ.2017.csv')
d2018 = pd.read_csv(ddir + 'stock.KOSPI.KOSDAQ.2018.csv')
d2019 = pd.read_csv(ddir + 'stock.KOSPI.KOSDAQ.2019.csv')
d2020 = pd.read_csv(ddir + 'stock.KOSPI.KOSDAQ.2020.csv')
d2021 = pd.read_csv(ddir + 'stock.KOSPI.KOSDAQ.2021.csv')

# mk_cd

In [3]:
## 함수
def mk_cd(x):
    if type(x) == str:
        if x.isalpha():
            return x
        else:
            if len(x) == 6:
                return x
            else:
                return "0"*(6-len(x))+x
    elif type(x) == int:
        x = str(x)
        return "0"*(6-len(x))+x

In [4]:
## 적용
d2012['code'] = list(map(mk_cd, d2012['code']))
d2013['code'] = list(map(mk_cd, d2013['code']))
d2014['code'] = list(map(mk_cd, d2014['code']))
d2015['code'] = list(map(mk_cd, d2015['code']))
d2016['code'] = list(map(mk_cd, d2016['code']))
d2017['code'] = list(map(mk_cd, d2017['code']))
d2018['code'] = list(map(mk_cd, d2018['code']))
d2019['code'] = list(map(mk_cd, d2019['code']))
d2020['code'] = list(map(mk_cd, d2020['code']))
d2021['code'] = list(map(mk_cd, d2021['code']))

# fillna (각 열의 평균으로)

## fillna 해야할 data 찾기

In [5]:
d2012.iloc[:,2:].isnull().sum().sum()
d2013.iloc[:,2:].isnull().sum().sum()
d2014.iloc[:,2:].isnull().sum().sum()
d2015.iloc[:,2:].isnull().sum().sum() #
d2016.iloc[:,2:].isnull().sum().sum() #
d2017.iloc[:,2:].isnull().sum().sum()
d2018.iloc[:,2:].isnull().sum().sum() #
d2019.iloc[:,2:].isnull().sum().sum()
d2020.iloc[:,2:].isnull().sum().sum() #
d2021.iloc[:,2:].isnull().sum().sum()


0

0

0

820

1640

0

820

0

820

0

## fillna

In [6]:
# fillna 잘 먹히는지 확인
# d2015.fillna(d2015.iloc[:,2:].mean()).isnull().sum().sum()
# d2016.fillna(d2015.iloc[:,2:].mean()).isnull().sum().sum()
# d2018.fillna(d2015.iloc[:,2:].mean()).isnull().sum().sum()
# d2020.fillna(d2015.iloc[:,2:].mean()).isnull().sum().sum()

d2015 = d2015.fillna(d2015.iloc[:,2:].mean())
d2016 = d2016.fillna(d2015.iloc[:,2:].mean())
d2018 = d2018.fillna(d2015.iloc[:,2:].mean())
d2020 = d2020.fillna(d2015.iloc[:,2:].mean())

## fillna test

In [155]:
d2015.iloc[:,2:].info()

# d2015.columns[-100:]
# d2015.iloc[:,2:].isnull().sum() # open 제외 모든 열에 nan값이 있음.

# 이 코드는 str이라고 에러남 # sum(d2015.iloc[:,2:].isnull())

# np.where(d2015.iloc[:,2:].isnull()) # null값인 곳 위치
d2015.iloc[162003,:]

d2015.iloc[:,2:].mean()
d2015.fillna(d2015.iloc[:,2:].mean()).isnull().sum().sum()
d2015.fillna(d2015.iloc[:,2:].mean()).iloc[162003,:] # 그냥 알아서 깥은 열의 빈 칸(null인 칸)에 넣어줌. 확인!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314361 entries, 0 to 314360
Columns: 821 entries, D-10_open to NextChange
dtypes: float64(821)
memory usage: 1.9 GB


date           20150206
code              28300
D-10_open          0.74
D-10_high           NaN
D-10_low            NaN
                 ...   
D-1_KST             NaN
D-1_DCW             NaN
D-1_SRSID           NaN
D-1_PPOhist         NaN
NextChange          NaN
Name: 162003, Length: 823, dtype: object

D-10_open       0.002667
D-10_high       0.031839
D-10_low       -0.025061
D-10_close      0.002356
D-10_MA5       -0.000125
                 ...    
D-1_KST        54.597840
D-1_DCW        20.674738
D-1_SRSID       0.485744
D-1_PPOhist     0.015459
NextChange      0.176403
Length: 821, dtype: float64

0

date            20150206
code               28300
D-10_open           0.74
D-10_high       0.031839
D-10_low       -0.025061
                 ...    
D-1_KST         54.59784
D-1_DCW        20.674738
D-1_SRSID       0.485744
D-1_PPOhist     0.015459
NextChange      0.176403
Name: 162003, Length: 823, dtype: object

# data 살펴보기

In [60]:
d2021['NextChange']

0        -2.38
1        -2.03
2        -0.83
3        -2.93
4        -0.43
          ... 
321803    0.47
321804    1.39
321805    1.37
321806    0.00
321807    0.00
Name: NextChange, Length: 321808, dtype: float64

In [17]:
d2021['code'].dtype # 이게 'Object'

dtype('O')

In [4]:
d2021.shape # (321808, 823)
d2021.info() # float64(821), int64(1), object(1)
# d2021.describe()
d2021.head() # 20210105
d2021.tail() # 20211209
d2021.columns.values # 식별변수: date, code, 설명변수(feature): D-10 ~ D-1, 목적변수: 'NextChange'


(321808, 823)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 321808 entries, 0 to 321807
Columns: 823 entries, date to NextChange
dtypes: float64(821), int64(1), object(1)
memory usage: 2.0+ GB


date   code  D-10_open  D-10_high  D-10_low  D-10_close  D-10_MA5  \
0  20210105  16385   0.011905   0.019841 -0.011905   -0.007937  0.007143   
1  20210106  16385   0.000000   0.000000 -0.032000   -0.032000  0.004800   
2  20210107  16385  -0.008264  -0.008264 -0.028926   -0.028926  0.022314   
3  20210108  16385  -0.008511  -0.008511 -0.038298   -0.038298  0.025532   
4  20210111  16385   0.000000   0.044248  0.000000    0.030973  0.049558   

   D-10_MA20  D-10_MA60  D-10_MA120  ...  D-1_VIpos  D-1_ROC  D-1_MFI  \
0   0.032540   0.032206    0.006611  ...    0.90698  -0.7874   46.303   
1   0.038600   0.038600    0.014400  ...    0.91667  -4.6512   47.839   
2   0.066736   0.070455    0.047826  ...    0.91608  -4.3651   45.077   
3   0.091277   0.100494    0.079251  ...    0.90780  -4.4000   39.347   
4   0.130088   0.143062    0.120274  ...    0.89051  -4.1322   39.125   

   D-1_KCW  D-1_BBP  D-1_KST  D-1_DCW  D-1_SRSID  D-1_PPOhist  NextChange  
0   6.7578  0.57316  -75.576   15.120    0.61641     0.059806       -2.38  
1   6.6263  0.47336  -79.124   15.145    0.74380     0.259040       -2.03  
2   6.9338  0.38046  -80.691   15.152    0.81864     0.259390       -0.83  
3   6.9195  0.35218  -77.558   15.126    0.78711     0.212530       -2.93  
4   7.0372  0.21853  -76.491   15.088    0.70221     0.005548       -0.43  

[5 rows x 823 columns]

date   code  D-10_open  D-10_high  D-10_low  D-10_close  D-10_MA5  \
321803  20211203  16380   0.000000   0.013699 -0.018265    0.009132  0.000000   
321804  20211206  16380   0.009050   0.054299 -0.004525   -0.004525 -0.010860   
321805  20211207  16380   0.004545   0.004545 -0.013636   -0.013636 -0.006364   
321806  20211208  16380   0.004608   0.004608 -0.013825   -0.013825  0.005530   
321807  20211209  16380   0.004673   0.009346 -0.037383   -0.032710  0.008411   

        D-10_MA20  D-10_MA60  D-10_MA120  ...  D-1_VIpos  D-1_ROC  D-1_MFI  \
321803   0.024201   0.188402    0.399817  ...    0.84663 -0.92166   54.026   
321804   0.011765   0.171584    0.380362  ...    0.92447  0.00000   59.601   
321805   0.012545   0.170545    0.379636  ...    1.00000  0.00000   64.319   
321806   0.023041   0.180461    0.391521  ...    1.04640  0.45249   68.930   
321807   0.032991   0.189720    0.404019  ...    1.02320  0.90909   67.728   

        D-1_KCW  D-1_BBP  D-1_KST  D-1_DCW  D-1_SRSID  D-1_PPOhist  NextChange  
321803   8.8876  0.49365 -106.380   20.566    0.46852      0.18908        0.47  
321804   8.5227  0.53138 -103.540   20.616    0.70950      0.56929        1.39  
321805   8.4022  0.63366 -100.020   14.870    0.89611      0.90618        1.37  
321806   8.1687  0.71497  -93.167   16.748    0.97162      1.19530        0.00  
321807   8.1120  0.70462  -85.850   16.684    1.00000      1.34680        0.00  

[5 rows x 823 columns]

array(['date', 'code', 'D-10_open', 'D-10_high', 'D-10_low', 'D-10_close',
       'D-10_MA5', 'D-10_MA20', 'D-10_MA60', 'D-10_MA120', 'D-10_MA240',
       'D-10_AO', 'D-10_KAMA', 'D-10_ADI', 'D-10_FI', 'D-10_VMAP',
       'D-10_BBH', 'D-10_BBL', 'D-10_BBM', 'D-10_DCH', 'D-10_DCL',
       'D-10_DCM', 'D-10_KCH', 'D-10_KCL', 'D-10_KCM', 'D-10_DPO',
       'D-10_Ichimoku_a', 'D-10_Ichimoku_b', 'D-10_ichimoku_base_line',
       'D-10_ichimoku_conversion_line', 'D-10_MACD', 'D-10_MACDdiff',
       'D-10_MACDsig', 'D-10_PSARdown', 'D-10_PSARup', 'D-10_CR',
       'D-10_DLR', 'D-10_PVO', 'D-10_SRSI', 'D-10_AIdown', 'D-10_STC',
       'D-10_RSI', 'D-10_EOMsig', 'D-10_NVI', 'D-10_ADXneg', 'D-10_WR',
       'D-10_AIup', 'D-10_rTR', 'D-10_VIneg', 'D-10_PVOsig', 'D-10_SO',
       'D-10_ATR', 'D-10_CMF', 'D-10_TSI', 'D-10_ADX', 'D-10_MI',
       'D-10_SRSIK', 'D-10_EOM', 'D-10_BBW', 'D-10_UI', 'D-10_ADXpos',
       'D-10_PPOsig', 'D-10_TRIX', 'D-10_volume', 'D-10_KSTsig',
       'D-10_CCI', 'D-10_t

In [6]:
d2012.shape

(284412, 823)

In [5]:
(np.array(d2012)).shape

(284412, 823)

In [181]:
d2015.describe()

date      D-10_open      D-10_high       D-10_low  \
count  3.143610e+05  314361.000000  314361.000000  314361.000000   
mean   2.015068e+07       0.002667       0.031839      -0.025061   
std    3.293646e+02       0.020612       0.041814       0.028807   
min    2.015010e+07      -0.300000      -0.299127      -0.300149   
25%    2.015042e+07      -0.004525       0.008712      -0.035787   
50%    2.015071e+07       0.000000       0.019830      -0.019841   
75%    2.015092e+07       0.009174       0.039956      -0.008573   
max    2.015123e+07       0.740000       0.301189       0.300385   

          D-10_close       D-10_MA5      D-10_MA20      D-10_MA60  \
count  314361.000000  314361.000000  314361.000000  314361.000000   
mean        0.002356      -0.000125      -0.005166      -0.020175   
std         0.042057       0.031586       0.089839       0.157525   
min        -0.300031      -0.296398      -0.701484      -0.830216   
25%        -0.017646      -0.013830      -0.047986      -0.104590   
50%         0.000000       0.000441      -0.002902      -0.022022   
75%         0.017097       0.014628       0.040313       0.063862   
max         0.301003       0.523684       3.255701       5.807724   

          D-10_MA120     D-10_MA240  ...      D-1_VIpos        D-1_ROC  \
count  314361.000000  314361.000000  ...  314361.000000  314361.000000   
mean       -0.038200      -0.069385  ...       0.991505       3.085585   
std         0.211013       0.299976  ...       0.145548      17.683378   
min        -0.882986      -0.912179  ...       0.398770     -87.079000   
25%        -0.158722      -0.230621  ...       0.891170      -6.219300   
50%        -0.043762      -0.085761  ...       0.996540       1.051200   
75%         0.073451       0.055683  ...       1.093900       9.090900   
max         5.318409       9.085211  ...       1.561600     996.810000   

             D-1_MFI        D-1_KCW        D-1_BBP        D-1_KST  \
count  314361.000000  314361.000000  314361.000000  314361.000000   
mean       55.975656      11.500938       0.541317      54.597840   
std        19.556164       4.849744       0.349341     212.717351   
min         0.000000       1.173400      -0.576340    -806.470000   
25%        41.752000       8.210000       0.264790     -53.038000   
50%        57.661000      10.394000       0.546020      24.531000   
75%        71.142000      13.536000       0.805900     114.120000   
max       100.000000     143.190000       1.588300    7511.900000   

             D-1_DCW      D-1_SRSID    D-1_PPOhist     NextChange  
count  314361.000000  314361.000000  314361.000000  314361.000000  
mean       20.674738       0.485744       0.015459       0.176403  
std        13.078155       0.313499       1.444424       4.529870  
min         4.923000       0.000000     -14.481000     -88.660000  
25%        12.645000       0.190360      -0.769870      -1.850000  
50%        17.178000       0.479080       0.001010       0.000000  
75%        24.542000       0.776430       0.750990       1.700000  
max       832.520000       1.000000      32.509000     631.430000  

[8 rows x 822 columns]

# arr test

In [63]:
tmp1 = np.array([[1,2],[3,4], [5,6]])
tmp1
tmp1.shape # 2차원; 3행, 2열
tmp2 = np.array([[7,8], [9,10]])
np.concatenate([tmp1,tmp2]) # 열 수가 같을 경우 아래로 이음
tmp1.reshape(2,-1)
np.concatenate([tmp1.reshape(2,-1),tmp2], axis = 1) # 행 수만 같으면 옆으로 이음
tmp1[0] # 0행
tmp1[0][0] # 0행, 0열
tmp1[:,-1] # 모든 행, 1열

array([[1, 2],
       [3, 4],
       [5, 6]])

(3, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

array([1, 2])

1

array([2, 4, 6])

In [75]:
tmp3 = np.array([[[1,2], [3,4], [5,6]]])
tmp3.shape # 3차원; depth: 1, row 3, col 2
tmp3
tmp3[0] # 0번째 dep
tmp4 = np.array([ [[1,2], [3,4]], [[5,6],[7,8]], [[9,10],[11,12]] ])
tmp4.shape # 3차원; depth: 3, row 2, col 2
tmp4
# tmp4[0] # 0번째 depth.
        # array([[1, 2],
        #       [3, 4]])
        
# tmp4[0][0] # 0번째 dep의 0번째 row. array([1, 2])

# tmp4[:,:,0] # 0번째 열들만, depth가 3개라 0번째 열들이 3개로 나눠져서 나옴.
            # array([[ 1,  3],
            #       [ 5,  7],
            #       [ 9, 11]])

# tmp3[:,:,0] # depth가 1개라 0번째 열들이 안나눠져서 나옴. array([[1, 3, 5]])

# tmp4[0][:,0] # 0번째 depth의 모든 행에 대한 0번째 열. array([1, 3])

# tmp4[:,0,:] # 0번째 행들만, depth가 3개라 0번째 행들이 3개로 나눠져서 나옴.
            # array([[ 1,  2],
            #       [ 5,  6],
            #       [ 9, 10]])
tmp4[:,:,:-1] # 모든 깊이, 모든 행에 대해 마지막 열의 직전까지

(1, 3, 2)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

array([[1, 2],
       [3, 4],
       [5, 6]])

(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]]])

In [86]:
tmp5 = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
tmp5

tmp6 = np.array([[[1,2,3],[4,5,6]],[[4,5,6]],[[7,8,9]]])
tmp6

tmp7 = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                 [[10,11,12], [13,14,15], [16,17,18]],
                 [[19,20,21], [22,23,24], [25,26,27]]])
tmp7

tmp7[::-1] # 깊이 단위로 거꾸로 reverse
tmp7[:,:,:-1] # 마지막 열 전까지 모든깊이, 모든 행, 그외 열
tmp7[:,:-1, :] # 마지막 행 전까지 모든 깊이, 모든 열, 그외 행
tmp7[:-1,:, :] # 마지막 깊이 전까지 모든 행, 모든 열, 그외 깊이
tmp7[:,:-1, :-1] # 마지막 행, 마지막 열 전까지 모든 깊이, 그외 행열

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

array([list([[1, 2, 3], [4, 5, 6]]), list([[4, 5, 6]]), list([[7, 8, 9]])],
      dtype=object)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

array([[[ 1,  2],
        [ 4,  5],
        [ 7,  8]],

       [[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[19, 20, 21],
        [22, 23, 24]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]],

       [[19, 20],
        [22, 23]]])

In [105]:
tmp7
# tmp7.reshape(-1,3,1) # 3행, 1열짜리로 reshape
# tmp7.reshape(-1,3) # 3열짜리, 2차원으로 reshape
# tmp7.reshape(-1,9) # 9열짜리 2차원으로 reshape
tmp7.reshape(-1,1).shape # 1열짜리로 reshape (27,1)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

(27, 1)

In [20]:
# 에러남. 실행 안됨. numpy_array = np.loadtxt(file, delimiter=",") 여기서 에러남
# ValueError: could not convert string to float: 'date'

# file = open(ddir + 'stock.KOSPI.KOSDAQ.2012.csv')
# numpy_array = np.loadtxt(file, delimiter=",")
# numpy_array

In [22]:
# 에러남. 실행 안됨. for row in reader: 여기서 에러남
# ValueError: could not convert string to float: 'date'

# import csv

# results = []
# with open(ddir + 'stock.KOSPI.KOSDAQ.2012.csv') as csvfile:
#     reader = csv.reader(csvfile, quoting=csv.QUOTE_NONNUMERIC) # change contents to floats
#     for row in reader: # each row is a list
#         results.append(row)

# csv to array test

In [28]:
# [csv to numpy methods](https://linuxhint.com/python-read-csv-2d-array/)
# Method 3: Using the Pandas Dataframe
Array2d_result = d2012.to_numpy()
# print(Array2d_result)
Array2d_result.shape

(284412, 823)

In [27]:
# Method 5: Using Pandas Dataframe Values
Array2d_result = d2012.values
# print(Array2d_result)
Array2d_result.shape

(284412, 823)

# csv to array

In [7]:
a2012 = d2012.to_numpy()
a2013 = d2013.to_numpy()
a2014 = d2014.to_numpy()
a2015 = d2015.to_numpy()
a2016 = d2016.to_numpy()
a2017 = d2017.to_numpy()
a2018 = d2018.to_numpy()
a2019 = d2019.to_numpy()
a2020 = d2020.to_numpy()
a2021 = d2021.to_numpy()

In [14]:
len(a2012)
len(a2013)
len(a2014)
len(a2015)
len(a2016)
len(a2017)
len(a2018)
len(a2019)
len(a2020)
len(a2021)

284412

242826

242448

314361

263593

216591

307395

278610

371006

321808

# feature selection 전에 먼저 그냥 돌려보기 (비교용), 회귀 모델 전체 한 번에 돌리기
* 3Y train,1Y test

## 3Y: a1214

In [13]:
a2012.shape[0] + a2013.shape[0] + a2014.shape[0]

a1214 = np.concatenate([a2012, a2013, a2014]) # 2차원 arr[행][열]

# np.concatenate([a2013, a2014, a2015])
# np.concatenate([a2014, a2015, a2016])
# np.concatenate([a2015, a2016, a2017])
# np.concatenate([a2016, a2017, a2018])
# np.concatenate([a2017, a2018, a2019])
# np.concatenate([a2018, a2019, a2020])
# np.concatenate([a2019, a2020, a2021])


769686

In [110]:
results = []
def my_regressor():
    X = a1214[:,:-1]
    y = a1214[:,-1]
    from sklearn.linear_model import LinearRegression # 일반 회귀 모델
    from sklearn.linear_model import Ridge, Lasso, ElasticNet # Norm 규제 회귀 모델
    from sklearn.linear_model import ARDRegression, BayesianRidge # 베이지안 회귀
    from sklearn.ensemble import RandomForestRegressor # decision tree 앙상블 모델, 배깅
    from xgboost import XGBRegressor # decision tree 앙상블 모델, 부스팅
#     from sklearn.model_selection import cross_val_score # model 검증
    
#     from sklearn.model_selection import StratifiedShuffleSplit
    from sklearn.model_selection import ShuffleSplit
    
    from sklearn.dummy import DummyRegressor
    from sklearn import metrics # 모델 평가 지표 for scoring (mse)
    
    import ast # convert string to function
    
    
#     ################################################### 전처리 파이프라인
#     from sklearn.pipeline import Pipeline
#     from sklearn.impute import SimpleImputer
#     from sklearn.preprocessing import MinMaxScaler

#     my_pipeline = Pipeline([('mean_imputer', SimpleImputer(strategy = 'mean')),
#                            ('mm_scaler', MinMaxScaler())])
    ##############################################################################

    
    linear = LinearRegression()
    ridge, lasso, elasticnet = Ridge(), Lasso(), ElasticNet()
    ardr_linear, baysian_ridge = ARDRegression(), BayesianRidge()
    random_forest = RandomForestRegressor()
    xgboost_linear = XGBRegressor()
    dummy = DummyRegressor(strategy = 'mean')
    
    my_model_list = ['linear', 'ridge', 'lasso', 'elasticnet',
                     'ardr_linear', 'baysian_ridge',
                     'random_forest', 'xgboost_linear', 'dummy']
    
    ######################################################################### fitting
    for model_nm in tqdm(my_model_list):
        
        # cv
        ss = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
        for train_idx, test_idx in tqdm(ss.split(X,y)):
            x_train = a1214[train_idx,2:-1] # 식별변수 제외 나머지 열 ~ NC열 전까지
            y_train = a1214[train_idx,-1]
            x_test = a1214[test_idx,2:-1] # 식별변수 제외 나머지 열 ~ NC열 전까지
            y_test = a1214[test_idx,-1]
            
            
            y_train = y_train.reshape(-1,1) # 1열짜리로 만드는 것
            y_test = y_test.reshape(-1,1)

#             # 전처리 (scaling)
#             x_train_fit = my_pipeline.fit(x_train)
#             x_train_pre = x_train_fit.transform(x_train)
#             x_test_pre = x_train_fit.transform(x_test)

#             y_train_fit = my_pipeline.fit(y_train)
#             y_train_pre = y_train_fit.transform(y_train)
#             y_test_pre = y_train_fit.transform(y_test)
            ########################################################
        
            # fitting
            model_ = eval(model_nm).fit(x_train, y_train)
            y_pred_test = model_.predict(x_test) # 예측

            mse_score = metrics.mean_squared_error(y_test, y_pred_test)

            results.append([i, f'{model_nm}', mse_score]) #[:str(model).index("(")]
            i+=1
            #####################################################################################
    
    return results#score_dic#[0]

In [114]:
_ = my_regressor()
results

# X, y; train, test

In [14]:
X_train = a1214[:,2:-1]
y_train = a1214[:,-1]
X_test = a2015[:,2:-1]
y_test = a2015[:,-1]

# linear regressor만 따로 돌리기

In [8]:
from sklearn.linear_model import LinearRegression # 일반 회귀 모델
linear = LinearRegression()
L_model = linear.fit(X_train, y_train)

## 예측

In [10]:
L_pred_train = L_model.predict(X_train)
L_pred_test = L_model.predict(X_test)

len(L_pred_train)
len(L_pred_test)

769686

314361

## MSE
- 가장 직관적, 그냥 오차?

In [189]:
d2015.median().sort_values()[550:]
# d2015.median().sort_values()[-10:]
d2015.median().mean()

D-1_VIpos           9.965400e-01
D-1_ROC             1.051200e+00
D-1_NVI             1.489800e+00
D-2_NVI             1.492400e+00
D-3_NVI             1.493800e+00
                        ...     
D-5_tradingvalue    9.872374e+08
D-4_tradingvalue    1.000063e+09
D-3_tradingvalue    1.007774e+09
D-2_tradingvalue    1.013455e+09
D-1_tradingvalue    1.018044e+09
Length: 272, dtype: float64

12563092.569550484

In [179]:
from sklearn import metrics # 모델 평가 지표 scoring (mse)
L_train_mse_score = metrics.mean_squared_error(y_train, L_pred_train)
L_test_mse_score = metrics.mean_squared_error(y_test, L_pred_test)

L_train_mse_score
L_test_mse_score

15.045480494154003

20.539773069241683

## R2 score
- 1에 가까울 수록 높은 성능의 모델

In [176]:
from sklearn.metrics import r2_score
# (y_true, y_pred, *, sample_weight=None, multioutput='uniform_average', force_finite=True)

In [177]:
r2_score(y_test, L_pred_test)

-0.0009804228689156425

# DecisionTreeRegressor
- 강력, 데이터에서 복잡한 비선형 관계를 찾을 수 있음.

In [ ]:
from sklearn.tree import DecisionTreeRegressor
DecisionTree = DecisionTreeRegressor()
D_model = DecisionTree.fit(X_train, y_train)

## 예측

### multiprocessing

In [13]:
from multiprocessing import Pool
p = Pool(5)
def f(x):
    return x*x
with p:
    p.map(f, [1,2,3])

p.close() # close를 해야함. (안하면 계산을 안멈춤.)

[1, 4, 9]

### multiprocessing, 내부 연산 비교

In [5]:
import numpy as np
from multiprocessing import Pool

arr = np.random.random(1000000)

def mul(x):
    return x * 10

In [22]:
%%time
# Serial Python
result = arr*10 # [mul(x) for x in arr]
result

CPU times: user 64.7 ms, sys: 0 ns, total: 64.7 ms
Wall time: 63.4 ms


array([0.0951484 , 6.89452034, 4.38690542, ..., 9.39343195, 6.04557671,
       7.98635604])

In [23]:
%%time
with Pool(processes=16) as p:
    result = arr*10#p.map(mul, arr)

CPU times: user 10.9 ms, sys: 9.56 s, total: 9.58 s
Wall time: 11.2 s


### ray

In [2]:
# pip install ray

In [19]:
ray.shutdown() # ray.init을 전에 했었다면 다시 init 하기 이전에 선행돼야 함. (혹은 init 후 바로 shutdown 실행, 혹은 init에 ignore_reinit_error=True 넣어주기)

In [8]:
%%time
import ray
import numpy as np
arr = np.random.random(1000000)

ray.init(num_cpus=16)

@ray.remote
def mul(x):
    return x * 10

arr = ray.put(arr)
result = ray.get(mul.remote(arr))
ray.shutdown()

CPU times: user 30.7 ms, sys: 73.8 ms, total: 104 ms
Wall time: 5.3 s


In [48]:
a2015.shape

(314361, 823)

In [49]:
a1215 = np.concatenate([a2012, a2013, a2014, a2015]) # 2차원 arr[행][열]
# X_train = a1215[:len(2015),2:-1]
# y_train = a1215[:len(2015),-1]
# X_test = a1215[len(a2015):,2:-1]
# y_test = a1215[len(a2015):,-1]

In [65]:
a1215.shape

(1084047, 823)

In [63]:
%%time
ray.init(num_cpus = 16) #, ignore_reinit_error=True

@ray.remote # 반드시 함수 바로 위에 씀. # 파이썬 함수나 클래스를 다른 프로세스에서 실행되는 Ray task로 만들어주는 데코레이터
def reg_modeling(X_y_train_test):
    
    X_train = ray.put(X_y_train_test[:len(a2015),2:-1]) # X_y_train_test[:len(2015),2:-1]
    y_train = ray.put(X_y_train_test[:len(a2015),-1]) # X_y_train_test[:len(2015),-1]
    X_test = ray.put(X_y_train_test[len(a2015):,2:-1]) # X_y_train_test[len(a2015):,2:-1]
    y_test = ray.put(X_y_train_test[len(a2015):,-1]) # X_y_train_test[len(a2015):,-1]
    
    from sklearn.linear_model import LinearRegression # 일반 회귀 모델
    linear = LinearRegression()
    L_model = linear.fit(X_train, y_train)
#     L_pred_train = L_model.predict(X_train)
    L_pred_test = L_model.predict(X_test)
    
    from sklearn import metrics # 모델 평가 지표 scoring (mse)
#     L_train_mse_score = metrics.mean_squared_error(y_train, L_pred_train)
    L_test_mse = metrics.mean_squared_error(y_test, L_pred_test)
    
    from sklearn.metrics import r2_score
    L_test_r2 = r2_score(y_test, L_pred_test)
    return L_test_mse, L_test_r2


ray_a1215 = ray.put(a1215) # put에는 1개의 input만 가능

results = ray.get(reg_modeling.remote(ray_a1215))
ray.shutdown()

ValueError: The remote function __main__.reg_modeling is too large (2218 MiB > FUNCTION_SIZE_ERROR_THRESHOLD=95 MiB). Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use ray.put() to put large objects in the Ray object store.

In [46]:
ray

<module 'ray' from '/home/gayoun0/.local/lib/python3.8/site-packages/ray/__init__.py'>

In [62]:
ray.shutdown()

In [56]:
results

NameError: name 'results' is not defined

In [8]:
d1215 = pd.concat([d2012, d2013, d2014, d2015])

In [69]:
# pip install pyarrow

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 29.4 MB 11.9 MB/s eta 0:00:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart the kernel to use updated packages.


In [10]:
# d1215.head()
d1215.reset_index(drop = True, inplace = True)

In [9]:
d1215.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1084047 entries, 0 to 314360
Columns: 823 entries, date to NextChange
dtypes: float64(821), int64(1), object(1)
memory usage: 6.7+ GB


In [124]:
'001'.isdigit()
type('01')

True

str

#### 'int'를 int로

In [144]:
for i in range(len(d1215['code'])):
#     d1215['code'][i]
#     break
    if type(d1215['code'][i]) == str and d1215['code'][i].isdigit():
            d1215['code'][i] = int(d1215['code'][i]) # d1215['code'][i].astype('int')
#     if type(d1215['code'][i]) == str and d1215['code'][i].isdigit()==False:
#             print(d1215['code'][i])
#             break

00781K


In [11]:
d1215['code'] = d1215['code'].astype('category')

In [145]:
d1215[d1215['code']=='000520']
d1215[d1215['code']=='00781K']

Empty DataFrame
Columns: [date, code, D-10_open, D-10_high, D-10_low, D-10_close, D-10_MA5, D-10_MA20, D-10_MA60, D-10_MA120, D-10_MA240, D-10_AO, D-10_KAMA, D-10_ADI, D-10_FI, D-10_VMAP, D-10_BBH, D-10_BBL, D-10_BBM, D-10_DCH, D-10_DCL, D-10_DCM, D-10_KCH, D-10_KCL, D-10_KCM, D-10_DPO, D-10_Ichimoku_a, D-10_Ichimoku_b, D-10_ichimoku_base_line, D-10_ichimoku_conversion_line, D-10_MACD, D-10_MACDdiff, D-10_MACDsig, D-10_PSARdown, D-10_PSARup, D-10_CR, D-10_DLR, D-10_PVO, D-10_SRSI, D-10_AIdown, D-10_STC, D-10_RSI, D-10_EOMsig, D-10_NVI, D-10_ADXneg, D-10_WR, D-10_AIup, D-10_rTR, D-10_VIneg, D-10_PVOsig, D-10_SO, D-10_ATR, D-10_CMF, D-10_TSI, D-10_ADX, D-10_MI, D-10_SRSIK, D-10_EOM, D-10_BBW, D-10_UI, D-10_ADXpos, D-10_PPOsig, D-10_TRIX, D-10_volume, D-10_KSTsig, D-10_CCI, D-10_tradingvalue, D-10_OBV, D-10_VPT, D-10_UO, D-10_SOsig, D-10_KCP, D-10_DCP, D-10_PVOhist, D-10_PPO, D-10_VIpos, D-10_ROC, D-10_MFI, D-10_KCW, D-10_BBP, D-10_KST, D-10_DCW, D-10_SRSID, D-10_PPOhist, D-9_open, D-9_high, D-9_low, D-9_close, D-9_MA5, D-9_MA20, D-9_MA60, D-9_MA120, D-9_MA240, D-9_AO, D-9_KAMA, D-9_ADI, D-9_FI, D-9_VMAP, D-9_BBH, D-9_BBL, ...]
Index: []

[0 rows x 823 columns]

date    code  D-10_open  D-10_high  D-10_low  D-10_close  \
550417  20140407  00781K   0.029228   0.029228 -0.039666   -0.037578   
550418  20140408  00781K   0.002169   0.040130 -0.003254    0.017354   
550419  20140409  00781K  -0.015991  -0.004264 -0.024520   -0.013859   
550420  20140410  00781K   0.009730   0.011892 -0.018378    0.006486   
550421  20140411  00781K   0.007519   0.007519 -0.016112    0.002148   
...          ...     ...        ...        ...       ...         ...   
798027  20151217  00781K   0.001653   0.057851  0.001653    0.006612   
798028  20151218  00781K   0.047619   0.047619 -0.014778   -0.011494   
798029  20151221  00781K   0.013289   0.071429 -0.011628    0.038206   
798030  20151222  00781K  -0.011200   0.038400 -0.024000    0.027200   
798031  20151223  00781K   0.000000   0.059190 -0.045171   -0.042056   

        D-10_MA5  D-10_MA20  D-10_MA60  D-10_MA120  ...  D-1_VIpos  D-1_ROC  \
550417 -0.011065  -0.049791  -0.123152   -0.078121  ...    1.00300 -2.30130   
550418  0.026030  -0.008134  -0.086161   -0.043557  ...    1.05640 -0.62762   
550419  0.001919  -0.021215  -0.099510   -0.061215  ...    1.04350  0.10438   
550420  0.010595  -0.002746  -0.084368   -0.049405  ...    1.02770  6.50760   
550421 -0.001289  -0.004554  -0.087583   -0.056907  ...    1.02350  5.22390   
...          ...        ...        ...         ...  ...        ...      ...   
798027 -0.006281   0.023471   0.083752    0.101901  ...    0.93773  0.00000   
798028 -0.011494   0.014039   0.074663    0.097044  ...    0.97059  0.16807   
798029  0.008638   0.026495   0.085963    0.111412  ...    0.99450 -1.81820   
798030 -0.013440  -0.009920   0.045440    0.071552  ...    0.99446 -1.80620   
798031 -0.036449  -0.037695   0.014019    0.042726  ...    0.99615 -1.99340   

        D-1_MFI  D-1_KCW  D-1_BBP  D-1_KST  D-1_DCW  D-1_SRSID  D-1_PPOhist  \
550417   37.018   8.8543  0.56774   79.951   8.6142    0.14311    -0.544920   
550418   48.504   8.7864  0.79536   76.356   6.8706    0.26543    -0.385970   
550419   52.456   8.2483  0.88694   72.481   6.8552    0.38684    -0.223770   
550420   60.181   8.2501  1.09960   72.184   9.7945    0.53046     0.026724   
550421   58.225   8.7501  1.07070   71.886   9.7365    0.66778     0.195450   
...         ...      ...      ...      ...      ...        ...          ...   
798027   64.126  10.2080  0.31141  -56.073  17.4570    0.38172    -0.013708   
798028   70.915  10.4920  0.28031  -54.801  17.4950    0.41502    -0.012175   
798029   74.443  10.7110  0.26864  -51.240  17.5180    0.44282    -0.017214   
798030   79.290  11.0440  0.35623  -49.645  17.5960    0.42600     0.037438   
798031   70.414  10.9700  0.24083  -51.123  17.7490    0.39469    -0.000454   

        NextChange  
550417        1.71  
550418        0.95  
550419        2.40  
550420        0.51  
550421        3.14  
...            ...  
798027       -0.50  
798028       -0.34  
798029        0.67  
798030       -1.34  
798031        0.00  

[340 rows x 823 columns]

In [100]:
d1215.head()

date   code  D-10_open  D-10_high  D-10_low  D-10_close  D-10_MA5  \
0  20120102  16385  -0.023573   0.009925 -0.028537    0.009925  0.000495   
1  20120103  16385   0.000000   0.000000  0.000000    0.000000 -0.005897   
2  20120104  16385   0.000000   0.007372  0.000000    0.007372 -0.002457   
3  20120105  16385  -0.001220   0.000000 -0.001220    0.000000 -0.006342   
4  20120110  16385  -0.002440   0.012194 -0.002440    0.012194  0.000975   

   D-10_MA20  D-10_MA60  D-10_MA120  ...  D-1_VIpos  D-1_ROC  D-1_MFI  \
0  -0.023078  -0.029591    0.049886  ...    1.14440  3.97020   86.354   
1  -0.028194  -0.039292    0.038472  ...    1.03640  2.48130   81.469   
2  -0.023772  -0.039374    0.037335  ...    1.12840  1.86100   78.376   
3  -0.027135  -0.046504    0.028606  ...    1.09180  0.61427   77.885   
4  -0.019270  -0.046993    0.026299  ...    0.95562 -2.43910   77.505   

   D-1_KCW  D-1_BBP  D-1_KST  D-1_DCW  D-1_SRSID  D-1_PPOhist  NextChange  
0   6.6468  0.89682   53.341   13.812   1.000000     0.289370       -1.43  
1   6.2073  0.70124   53.597   13.308   0.912360     0.155670       -0.61  
2   6.1898  0.60901   53.290   13.296   0.713610     0.012119       -0.24  
3   5.9693  0.55773   53.453   13.298   0.403750    -0.106770       -0.24  
4   5.9335  0.13632   51.280   15.881   0.023473    -0.398300        0.00  

[5 rows x 823 columns]

In [105]:
type(d1215['code'][0])
d1215['code'].dtype
type(d1215['date'][0])
type(d1215['D-10_open'][0])

int

CategoricalDtype(categories=[      20,       30,       40,       50,       60,       70,
                        75,       80,       87,      100,
                  ...
                  '036530', '041460', '052900', '069260', '085660', '085670',
                  '123410', '126600', '126640', '18064K'],
, ordered=False)

numpy.int64

numpy.float64

In [12]:
d1215.to_feather('d1215.ftr')

# inhovation code

In [ ]:
from multiprocessing import Pool
import multiprocessing
import itertools
start_time=time.time()
processes = 30

# 멀티프로세싱 argument 생성
# IF = open(file_name, 'r')
# args_list=[]
# for i,row in enumerate(IF):
#     code = row.split('\n')[0]
#     args_list.append([code, fold, mode])
# IF.close()

result = []
# 멀티프로세싱 진행
pool = multiprocessing.Pool(processes = processes)
for data in pool.starmap(a1214, args_list ): # 각 코어에 입력값들을 병렬 처리
    result+=data
pool.close() # 멀티 프로세싱 종료
pool.join()


print("--- %s seconds ---" % (time.time() - start_time))


In [ ]:
D_pred_train = D_model.predict(X_train)
D_pred_test = D_model.predict(X_test)

# 하이퍼 파라미터 조정

In [175]:
a2015.shape
X_test.shape
pred_test.shape

(314361, 823)

(314361, 820)

(314361,)

In [130]:
sum(sum(a2015 == 'NaN')) # arr로는 NaN 해결 안될 것 같음. 따로 구글링 안함.

0