In [2]:
from tqdm import tqdm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# CCI 직접 만들어보기
(성공했는지 여부는 확인 안함...)

# M_lst부터

In [3]:

# cd_dt_dic = {}
# x_df = []
# y_df = []
# minmax_idx = []
M_lst = []

f = open('stock_2018.csv')
lines = f.readlines()
for i, line in tqdm(enumerate(lines)):
    line = line.strip()
    lst = line.split(',')
    lst = lst[1:]
    
    if i == 0:
#         cd = lst.index('Code') # 0
#         dt = lst.index('Date') # 1
#         nc = lst.index('Next_Change') # 9
#         tv = lst.index('Trading_Value') # 7
#         ma = lst.index('MA20') # 11
        hi = lst.index('High') # 3
        lo = lst.index('Low') # 4
        cl = lst.index('Close') # 5
        
#         for mm in ['Open', 'High', 'Low', 'Close', 'MA5', 'MA20', 'MA60', 'MA120', 'VMAP', 'BHB', 'BLB', 'KCH', 'KCL', 'KCM', 'DCH', 'DCL', 'DCM','SMA', 'EMA', 'WMA', 'Ichimoku', 'Parabolic_SAR', 'KAMA','MACD']:
#             minmax_idx.append(lst.index(mm))
#         minmax_idx = sorted(minmax_idx)
    else:
        M = 0
        for i in (hi,lo,cl):
            M += float(lst[i])
        M_lst.append(M/3)
#         m = float(lst[ma])
#         d = abs(M-m)
#         d
#         break
#         cci = 

380590it [00:01, 341846.68it/s]


In [23]:
N = 20
m_lst = []
# cnt = 0

for i in range(len(M_lst)):
    if i >= len(M_lst)-20:
#         cnt+=1
        pass
    else:
        m = sum(M_lst[i:i+N]) / N
        m_lst.append(m)

In [26]:
len(M_lst)
len(m_lst)
# m_lst[-1]
# cnt

380589

380589

0

In [25]:
m_lst.extend([0]*20)

In [35]:
import numpy as np
d_lst = []
for i in range(len(M_lst)):
    if i >= len(M_lst)-20:
        pass
    else:
        d = abs(sum(np.array(M_lst[i:i+N]) - np.array(m_lst[i:i+N]))) / N
        d_lst.append(d)

In [38]:
m_lst[:2]
d_lst[:2]
len(d_lst)

[13757.5, 14054.999999999996]

[991.5833333333343, 739.6250000000008]

380589

In [37]:
d_lst.extend([0]*20)

In [39]:
cci_lst = []
for i in range(len(M_lst)):
    if i >= len(M_lst)-20:
        pass
    else:
        cci = (M_lst[i]-m_lst[i]) / 0.015 * d_lst[i]
        cci_lst.append(cci)

In [46]:
len(cci_lst)
cci_lst.extend([0]*20)

380569

In [48]:
len(cci_lst)
max(cci_lst)

380589

26267508077020.98

# cci again with 참고 코드
[참고](https://superhky.tistory.com/321)

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame(M_lst, columns = ['AP'])
df['SMA'] = df['AP'].rolling(20).mean()
df['ADV'] = df['AP'].rolling(20).apply(lambda x:pd.Series(x).mad())
df['CCI'] = (df['AP'] - df['SMA']) / (0.015 * df['ADV'])
df

AP          SMA         ADV         CCI
0       11333.333333          NaN         NaN         NaN
1       11700.000000          NaN         NaN         NaN
2       12783.333333          NaN         NaN         NaN
3       12466.666667          NaN         NaN         NaN
4       12866.666667          NaN         NaN         NaN
...              ...          ...         ...         ...
380584   4430.000000  4835.916667  158.916667 -170.284915
380585   4496.666667  4808.750000  162.958333 -127.674082
380586   4420.000000  4777.083333  165.958333 -143.442966
380587   4460.000000  4747.833333  169.933333 -112.920099
380588   4656.666667  4728.833333  161.950000  -29.707386

[380589 rows x 4 columns]

In [56]:
df['CCI'].max()
df['CCI'].min()

666.6666666666691

-666.6666666666692

# cci 저장 및 확인

In [57]:
# df.to_csv('CCI.csv', index = False)

In [58]:
pd.read_csv('CCI.csv')

AP          SMA         ADV         CCI
0       11333.333333          NaN         NaN         NaN
1       11700.000000          NaN         NaN         NaN
2       12783.333333          NaN         NaN         NaN
3       12466.666667          NaN         NaN         NaN
4       12866.666667          NaN         NaN         NaN
...              ...          ...         ...         ...
380584   4430.000000  4835.916667  158.916667 -170.284915
380585   4496.666667  4808.750000  162.958333 -127.674082
380586   4420.000000  4777.083333  165.958333 -143.442966
380587   4460.000000  4747.833333  169.933333 -112.920099
380588   4656.666667  4728.833333  161.950000  -29.707386

[380589 rows x 4 columns]

In [6]:
pd.read_csv('stock_2018.csv')

Index   Code        Date   Open   High    Low  Close    Volume  \
0           243  50120  2018-01-02  10250  12050  10150  11800  26086769   
1           244  50120  2018-01-03  11950  12450  10900  11750  20460474   
2           245  50120  2018-01-04  11850  14150  11600  12600  60663854   
3           246  50120  2018-01-05  12800  13200  12000  12200  13935258   
4           247  50120  2018-01-08  12450  13400  12350  12850  16471707   
...         ...    ...         ...    ...    ...    ...    ...       ...   
380584  1913939    540  2018-12-21   4480   4480   4330   4480    109164   
380585  1913940    540  2018-12-24   4480   4530   4440   4520     36973   
380586  1913941    540  2018-12-26   4515   4515   4275   4470     28747   
380587  1913942    540  2018-12-27   4475   4500   4410   4470     20617   
380588  1913943    540  2018-12-28   4500   4825   4440   4705     60012   

        Trading_Value    Change  ...      SRSI      TSI       UO       SR  \
0        307823874200  0.145631  ...  0.617452  22.3595  45.6450  73.6842   
1        240410569500 -0.004237  ...  0.606881  24.6104  44.5857  72.7096   
2        764364560400  0.072340  ...  0.691669  27.8890  46.0102  74.7145   
3        170010147600 -0.031746  ...  0.605418  28.9426  46.8657  67.9276   
4        211661434950  0.053279  ...  0.670468  30.8389  48.7672  78.6184   
...               ...       ...  ...       ...      ...      ...      ...   
380584      489054720  0.000000  ...  0.000000 -48.1839  40.9134  21.4286   
380585      167117960  0.008929  ...  0.250801 -48.6931  47.1329  27.1429   
380586      128499090 -0.011062  ...  0.177769 -49.7125  54.1570  27.2727   
380587       92157990  0.000000  ...  0.291459 -50.5188  54.6350  28.4672   
380588      282356460  0.052573  ...  1.000000 -42.8563  62.2204  73.5043   

             WR        AO      KAMA       ROC      PPO       PVO  
0      -26.3158  1259.470   9897.76  44.78530  6.24021  42.05600  
1      -27.2904  1435.350  10067.00  44.17180  7.16213  36.42410  
2      -25.2855  1988.650  10221.40  53.09840  8.40391  42.40620  
3      -32.0724  2473.210  10308.60  51.17720  8.92074  34.04080  
4      -21.3816  2793.380  10359.80  26.60100  9.65555  27.63640  
...         ...       ...       ...       ...      ...       ...  
380584 -78.5714  -363.397   4592.44 -10.31030 -3.14961   2.96624  
380585 -72.8571  -394.015   4580.40  -8.87097 -3.21322   3.55599  
380586 -72.7273  -422.632   4560.38  -7.83505 -3.31474   2.02404  
380587 -71.5328  -430.515   4538.92  -6.58307 -3.35971  -1.25023  
380588 -26.4957  -402.265   4540.78  -1.36268 -2.95350   5.69357  

[380589 rows x 60 columns]

# FDR

In [8]:
import FinanceDataReader as fdr

In [26]:
# 한국거래소 상장종목 전체...
# 교수님 데이터는 KRX 전체인 것으로 판단...

df_krx = fdr.StockListing('KRX')
df_krx.head()

Symbol  Market    Name           Sector             Industry ListingDate  \
0  060310  KOSDAQ      3S         전자부품 제조업          반도체 웨이퍼 캐리어  2002-04-23   
1  095570   KOSPI  AJ네트웍스  산업용 기계 및 장비 임대업  렌탈(파렛트, OA장비, 건설장비)  2015-08-21   
2  006840   KOSPI   AK홀딩스           기타 금융업                 지주사업  1999-08-11   
3  054620  KOSDAQ  APS홀딩스           기타 금융업          인터넷 트래픽 솔루션  2001-12-04   
4  265520  KOSDAQ   AP시스템    특수 목적용 기계 제조업          디스플레이 제조 장비  2017-04-07   

  SettleMonth     Representative                       HomePage Region  
0         03월                김세완           http://www.3sref.com  서울특별시  
1         12월           박대현, 손삼달         http://www.ajnet.co.kr  서울특별시  
2         12월  채형석, 이석주(각자 대표이사)  http://www.aekyunggroup.co.kr  서울특별시  
3         12월                정기로   http://www.apsholdings.co.kr    경기도  
4         12월                김영주     http://www.apsystems.co.kr    경기도

In [12]:
fdr.DataReader('005930', '2017')

Open   High    Low  Close    Volume    Change
Date                                                      
2017-01-02  35980  36240  35880  36100     93012  0.001665
2017-01-03  36280  36620  36020  36480    147153  0.010526
2017-01-04  36500  36520  36100  36160    159435 -0.008772
2017-01-05  36060  36060  35540  35560    219349 -0.016593
2017-01-06  36180  36440  36040  36200    177619  0.017998
...           ...    ...    ...    ...       ...       ...
2022-03-24  69600  70300  69600  69800  37943357 -0.009929
2022-03-25  70100  70200  69600  69800  12986010  0.000000
2022-03-28  69500  69900  69200  69700  12619289 -0.001433
2022-03-29  70000  70300  69800  70200  13686208  0.007174
2022-03-30  70300  70500  69800  69900  12348445 -0.004274

[1287 rows x 6 columns]

## df2017

In [124]:
# 'ListingDate' 열 type str으로 바꾸기. (2017 판단 위해)
from datetime import datetime
df_krx1 = df_krx.copy()

# df_krx1['ListingDate'] = list(map(lambda x : x.strftime("%Y%m%d") if pd.notna(x) else x, df_krx1['ListingDate'])) #= #['Name']
df_krx1['ListingDate'] = list(map(lambda x : int(x.strftime("%Y")) if pd.notna(x) else x, df_krx1['ListingDate']))
df_krx1

Symbol  Market             Name                    Sector  \
0     060310  KOSDAQ               3S                  전자부품 제조업   
1     095570   KOSPI           AJ네트웍스           산업용 기계 및 장비 임대업   
2     006840   KOSPI            AK홀딩스                    기타 금융업   
3     054620  KOSDAQ           APS홀딩스                    기타 금융업   
4     265520  KOSDAQ            AP시스템             특수 목적용 기계 제조업   
...      ...     ...              ...                       ...   
7926  000545   KOSPI            흥국화재우                       NaN   
7927  003280   KOSPI             흥아해운                    해상 운송업   
7928  037440  KOSDAQ               희림  건축기술, 엔지니어링 및 관련 기술 서비스업   
7929  419890   KOSPI  히어로즈 단기채권ESG액티브                       NaN   
7930  238490  KOSDAQ               힘스             특수 목적용 기계 제조업   

                            Industry ListingDate SettleMonth  \
0                        반도체 웨이퍼 캐리어        2002         03월   
1                렌탈(파렛트, OA장비, 건설장비)        2015         12월   
2                               지주사업        1999         12월   
3                        인터넷 트래픽 솔루션        2001         12월   
4                        디스플레이 제조 장비        2017         12월   
...                              ...         ...         ...   
7926                             NaN         NaT         NaN   
7927                  외항화물운송업(케미컬탱커)        1976         12월   
7928                       설계 및 감리용역        2000         12월   
7929                             NaN         NaT         NaN   
7930  OLED Mask 인장기, OLED Mask 검사기 등        2017         12월   

            Representative                       HomePage Region  
0                      김세완           http://www.3sref.com  서울특별시  
1                 박대현, 손삼달         http://www.ajnet.co.kr  서울특별시  
2        채형석, 이석주(각자 대표이사)  http://www.aekyunggroup.co.kr  서울특별시  
3                      정기로   http://www.apsholdings.co.kr    경기도  
4                      김영주     http://www.apsystems.co.kr    경기도  
...                    ...                            ...    ...  
7926                   NaN                            NaN    NaN  
7927                   이환구         http://www.heung-a.com  서울특별시  
7928  정영균, 이목운, 허철호 (각자대표)          http://www.heerim.com  서울특별시  
7929                   NaN                            NaN    NaN  
7930                   김주환          http://www.hims.co.kr  인천광역시  

[7931 rows x 10 columns]

In [132]:
len(list(df_krx1['Symbol'][df_krx1['ListingDate']<=2017].values)) # 1992
data2017 = list(df_krx1['Symbol'][df_krx1['ListingDate']<=2017].values)

1992

In [139]:
# 파일 저장 test
for cd in data2017:
#     print(f'{cd},', end = '')
    print(f'{cd}\n')

060310

095570

006840

054620

265520

211270

027410

282330

032790

138930

001460

013720

001040

079160

035760

000120

011150

097950

051500

058820

023460

056730

056000

065770

083660

000590

012030

016610

005830

000990

139130

001530

000210

001880

068790

004840

241520

155660

069730

017940

037370

278990

079190

050120

007700

214270

130500

114090

900290

078930

083450

006360

001250

007070

078150

012630

039570

089470

097230

028300

067630

047920

115450

011200

036640

082740

003560

095340

099520

175330

234080

067290

001060

096760

035900

024840

105560

024120

002380

021320

036670

009070

009440

112190

119650

044180

092220

151860

016380

046440

035600

001390

226360

111870

033180

060720

001940

122450

052900

058400

114450

025000

092230

000040

044450

030200

033780

030210

058850

058860

060370

093050

003550

034220

051900

032640

011070

066570

037560

051910

079550

006260

010120

000680

229640



## 2017까지 상장한 기업 code 담긴 파일 저장

In [140]:
# with open('data2017.txt', 'w', encoding = 'UTF-8') as f:
#     for cd in data2017:
#         _ = f.write(f'{cd}\n')

## code 담긴 file load 해서 df 하나로 합치기 (df2017)

In [174]:
f = open(f'data2017.txt', 'r', encoding = 'utf-8')
lines = f.readlines()
df2017 = pd.DataFrame()
for line in lines:
    cd = line.strip()
    tmp = fdr.DataReader(cd, start = '2017-01-01', end = '2017-12-31')
#     tmp
#     tmp.index
    tmp_cd = pd.DataFrame([cd] * len(tmp))# pd.Series([cd] * len(tmp), name = 'Code')
    tmp_cd.index = tmp.index # 원랜 안해줘도 됐는데 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
    tmp_cd.columns = ['Code'] # 원랜 안해줘도 됐는데 이번엔 안해줬더니 이상하게 받길래... (axis 문제인지 확인해봤지만 아닌듯 보였음.)
#     tmp_cd
    
    # 옆으로 이어붙이기
    fin_tmp = pd.concat([tmp_cd, tmp], axis = 1) # 아니 axis = 1 안했을 때 왜 옆으로 들어간 것처럼 보여선 헷갈리게...
    
    # 아래로 이어붙이기, 이름 덮어써야 계속 이어붙음.
    df2017 = pd.concat([df2017, fin_tmp])

In [176]:
len(df2017)
df2017

470211

Code   Open   High    Low  Close  Volume    Change
Date                                                            
2017-01-02  060310   2820   3035   2790   3000  478672  0.077199
2017-01-03  060310   3070   3070   2900   3030  309507  0.010000
2017-01-04  060310   3030   3095   2980   3090  248971  0.019802
2017-01-05  060310   3090   3300   3050   3090  928979  0.000000
2017-01-06  060310   3090   3095   3015   3015  202702 -0.024272
...            ...    ...    ...    ...    ...     ...       ...
2017-12-21  238490  12247  12322  11721  11746   63187 -0.033012
2017-12-22  238490  11821  12021  11320  12022   59108  0.023497
2017-12-26  238490  12021  12021  11771  11821   34625 -0.016719
2017-12-27  238490  11821  11996  11620  11796   46955 -0.002115
2017-12-28  238490  11871  12071  11821  11997   50542  0.017040

[470211 rows x 7 columns]

In [177]:
# df2017.to_csv('df2017.csv')

In [178]:
pd.read_csv('df2017.csv')

Date    Code   Open   High    Low  Close  Volume    Change
0       2017-01-02   60310   2820   3035   2790   3000  478672  0.077199
1       2017-01-03   60310   3070   3070   2900   3030  309507  0.010000
2       2017-01-04   60310   3030   3095   2980   3090  248971  0.019802
3       2017-01-05   60310   3090   3300   3050   3090  928979  0.000000
4       2017-01-06   60310   3090   3095   3015   3015  202702 -0.024272
...            ...     ...    ...    ...    ...    ...     ...       ...
470206  2017-12-21  238490  12247  12322  11721  11746   63187 -0.033012
470207  2017-12-22  238490  11821  12021  11320  12022   59108  0.023497
470208  2017-12-26  238490  12021  12021  11771  11821   34625 -0.016719
470209  2017-12-27  238490  11821  11996  11620  11796   46955 -0.002115
470210  2017-12-28  238490  11871  12071  11821  11997   50542  0.017040

[470211 rows x 8 columns]

## 2017 M_lst (M_lst는 cci지수 만들 때 필요한 것.)

In [194]:
M_lst2017 = []

f = open('df2017.csv')
lines = f.readlines()
for i, line in tqdm(enumerate(lines)):
    line = line.strip()
    lst = line.split(',')
    
    if i == 0:
        hi = lst.index('High') # 3
        lo = lst.index('Low') # 4
        cl = lst.index('Close') # 5
    else:
        M = 0
        for i in (hi,lo,cl):
#             'i', i, 'lst[i]:', lst[i]
            M += int(lst[i])
        M_lst2017.append(M/3)

470212it [00:00, 666339.86it/s]


## 2017 CCI

In [195]:
cci2017 = pd.DataFrame(M_lst2017, columns = ['AP']) #M
cci2017['SMA'] = cci2017['AP'].rolling(20).mean() #m
cci2017['ADV'] = cci2017['AP'].rolling(20).apply(lambda x:pd.Series(x).mad()) #d
cci2017['CCI'] = (cci2017['AP'] - cci2017['SMA']) / (0.015 * cci2017['ADV']) #cci
cci2017

AP           SMA         ADV         CCI
0        2941.666667           NaN         NaN         NaN
1        3000.000000           NaN         NaN         NaN
2        3055.000000           NaN         NaN         NaN
3        3146.666667           NaN         NaN         NaN
4        3041.666667           NaN         NaN         NaN
...              ...           ...         ...         ...
470206  11929.666667  13111.183333  613.150000 -128.464124
470207  11787.666667  12987.633333  617.300000 -129.593031
470208  11871.000000  12854.466667  582.480000 -112.560851
470209  11804.000000  12725.883333  539.571667 -113.903106
470210  11963.000000  12638.250000  510.700000  -88.146988

[470211 rows x 4 columns]

In [196]:
# cci2017.to_csv('CCI2017.csv', index = False)

In [197]:
pd.read_csv('CCI2017.csv')

AP           SMA         ADV         CCI
0        2941.666667           NaN         NaN         NaN
1        3000.000000           NaN         NaN         NaN
2        3055.000000           NaN         NaN         NaN
3        3146.666667           NaN         NaN         NaN
4        3041.666667           NaN         NaN         NaN
...              ...           ...         ...         ...
470206  11929.666667  13111.183333  613.150000 -128.464124
470207  11787.666667  12987.633333  617.300000 -129.593031
470208  11871.000000  12854.466667  582.480000 -112.560851
470209  11804.000000  12725.883333  539.571667 -113.903106
470210  11963.000000  12638.250000  510.700000  -88.146988

[470211 rows x 4 columns]

# CCI 1718
* 17, 18 나눠서 하면 소용 없음;;;
* M_lst도 잘못됨. 위의 방식처럼 종목별로 안나눠서 하면 안됨...

# 아래는 test

In [64]:
# strftime test
df_krx1['ListingDate'][100].strftime("%Y-%m-%d")
type(df_krx1['ListingDate'][100])

'2017-10-31'

pandas._libs.tslibs.timestamps.Timestamp

In [115]:
# NaT 확인 test
import numpy as np
df_krx1['ListingDate'][6]== pd.NaT ######## 잘못됨
pd.isnull(df_krx1['ListingDate'][6]) ################ 정답 (원하던 결과)
pd.notnull(df_krx1['ListingDate'][6]) ################### 정답 (원하던 결과)
'#~~~%$^@$~~%&'
np.where(df_krx1['ListingDate'].isnull())
np.where(df_krx1['ListingDate'].isna())
np.where(df_krx1['ListingDate'].notnull())
np.where(df_krx1['ListingDate'].notna())
df_krx1['ListingDate'][:10]

False

True

False

'#~~~%$^@$~~%&'

(array([   6,    7,    8, ..., 7925, 7926, 7929]),)

(array([   6,    7,    8, ..., 7925, 7926, 7929]),)

(array([   0,    1,    2, ..., 7927, 7928, 7930]),)

(array([   0,    1,    2, ..., 7927, 7928, 7930]),)

0   2002-04-23
1   2015-08-21
2   1999-08-11
3   2001-12-04
4   2017-04-07
5   2016-03-04
6          NaT
7          NaT
8          NaT
9          NaT
Name: ListingDate, dtype: datetime64[ns]

In [95]:
# df_krx1[['ListingDate']].info()
# df_krx1[['ListingDate']].describe()
df_krx1[['ListingDate']].value_counts()

ListingDate
1996-07-03     8
1976-06-30     8
1999-12-21     7
1994-12-29     7
1996-12-24     7
              ..
2006-06-29     1
2006-06-27     1
2006-06-23     1
2006-06-08     1
2022-03-28     1
Length: 1857, dtype: int64