In [1]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
s17_re = pd.read_csv('s17_re.csv')

In [4]:
s18 = pd.read_csv('stock_2018.csv')

In [10]:
(s18['Date'].str.contains('2017-').values == 1).sum()

0

In [11]:
s17_re.columns

s_all = pd.concat([s17_re,s18[s17_re.columns]])
s_all = s_all.sort_values(['Code', 'Date']).reset_index(drop = True)[['Code', 'Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Change']] # code, date로 정렬
s_all

Index(['Date', 'Code', 'Open', 'High', 'Low', 'Close', 'Volume', 'Change'], dtype='object')

Code        Date   Open   High    Low  Close   Volume    Change
0           20  2017-11-01   8850   9170   8840   9170   115335  0.037330
1           20  2017-11-02   9170   9180   9030   9100    68630 -0.007634
2           20  2017-11-03   9080   9270   9070   9240   117255  0.015385
3           20  2017-11-06   9300   9500   9270   9490   369895  0.027056
4           20  2017-11-07   9500   9530   9260   9340   166998 -0.015806
...        ...         ...    ...    ...    ...    ...      ...       ...
461749  950160  2017-12-21  44650  46150  43500  43500  1077534 -0.003436
461750  950160  2017-12-22  44350  45250  43600  44500   816742  0.022989
461751  950160  2017-12-26  44200  46800  44200  45250   960367  0.016854
461752  950160  2017-12-27  46600  49500  46100  49500  1324792  0.093923
461753  950160  2017-12-28  51100  53300  50200  51800  1587974  0.046465

[461754 rows x 8 columns]

In [29]:
# 고려해야할 사항
# 상장년도가 18년
# 마지막 거래된 년도가 17년

461754 - 11948 # == 440806은 이번 주피터에서의 s_all 이란 df의 길이 

449806 - 444549 # 444549는 이전 주피터에서의 s_all_cp (stock1718_clean으로 저장되는.. 17년도가 마지막 거래년도였던 애들을 뺀...) 이란 df 길이

449806

5257

In [65]:
s_all['Code'].unique()
# s_all.groupby('Code').max('Date')
(s_all.groupby('Code')['Date'].max().str.contains('2017-')==1)

len(s_all['Code'].unique()[s_all.groupby('Code')['Date'].max().str.contains('2017-')==1])
del_cd_nms = s_all['Code'].unique()[s_all.groupby('Code')['Date'].max().str.contains('2017-')==1]

# s_all[s_all.groupby('Code')['Date'].max('Date')] # 이전 주피터에서 막 이런 식으러 했던 이건 틀림;;;
# ['Date'].str.contains('2017-').values == 1

array([    20,     40,     50, ..., 950130, 950140, 950160])

Code
20        False
40        False
50        False
60        False
70        False
          ...  
900310     True
950110    False
950130    False
950140     True
950160     True
Name: Date, Length: 1993, dtype: bool

432

# del_cd_nms에 18년도에도 있는 cd가 포함돼있는지 여부 확인 cell

In [75]:
for i in del_cd_nms:
#     s_all[s_all['Code'] == i]['Date'].str.contains('2018-')==1
    if (s_all[s_all['Code'] == i]['Date'].str.contains('2018-')).sum()>0:
        print(i)
# 출력된게 없는걸봐선 17이 마지막인 코드 중에 18을 포함하는건 없단소린데.....

In [27]:
s_all['Code'].unique()
s_all['Code'].nunique()
s_all['Code'][s_all['Date'].str.contains('2017-12-2').values == 1].unique()#.groupby('Code').max('Date')
s_all['Code'][s_all['Date'].str.contains('2017-12-2').values == 1].nunique()

s_all['Code'][s_all['Date'].str.contains('2017-12-2').values == 1].index # 이건 그냥 '2017-12-2가 들어있는 date가 있는 idx들이고...'

array([    20,     40,     50, ..., 950130, 950140, 950160])

1993

array([    20,     40,     50, ..., 950130, 950140, 950160])

1992

Int64Index([    35,     36,     37,     38,     39,     40,    320,    321,
               322,    323,
            ...
            461712, 461713, 461714, 461715, 461748, 461749, 461750, 461751,
            461752, 461753],
           dtype='int64', length=11948)

In [ ]:
df = pd.DataFrame(M_lst, columns = ['AP'])
df['SMA'] = df['AP'].rolling(20).mean()
df['ADV'] = df['AP'].rolling(20).apply(lambda x:pd.Series(x).mad())
df['CCI'] = (df['AP'] - df['SMA']) / (0.015 * df['ADV'])
df